package:
  name: conda
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv && {{ PYTHON }} -m conda init --install
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                    # [unix]
    - bin/activate                 # [unix]
    - bin/deactivate               # [unix]
    - Scripts/activate.bat         # [win]
    - Scripts/activate             # [win]
    - Scripts/deactivate           # [win]

requirements:
  build:
    - git  # for source/git_url above
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - wheel
    # for `conda init` in build/script above
    - menuinst >=1.4.11,<2         # [win]
    - requests >=2.27.0,<3
    - ruamel.yaml >=0.11.14,<0.18
    - tqdm >=4
    - pysftp >=0.2.9
  run:
    - boltons >=23.0.0
    - conda-package-handling >=2.2.0
    - jsonpatch >=1.32
    - menuinst >=1.4.11,<2         # [win]
    - packaging >=23.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python
    - requests >=2.27.0,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0           # [py>=310]
    - pysftp >=0.2.9
  run_constrained:
    - conda-build >=3.18.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0

test:
  imports:
    # high-level imports
    - conda
    - conda_env
    # new/updated submodules (can be dropped after 1-2 releases)
    - conda.gateways.repodata.jlap
    - conda.plugins.subcommands.doctor
  commands:
    # builtin subcommands
    - conda --help
    - conda clean --help
    - conda compare --help
    - conda config --help
    - conda create --help
    - conda info --help
    - conda init --help
    - conda install --help
    - conda list --help
    - conda notices --help
    - conda package --help
    - conda remove --help
    - conda rename --help
    - conda run --help
    - conda search --help
    - conda update --help
    - conda upgrade --help
    # plugin subcommands
    - conda doctor --help

about:
  home: https://conda.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Canary release of conda
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/conda
